nodeLinker: node-modules

packageExtensions:
  '@commitlint/load@*':
    dependencies:
      '@types/node': '*'
      'typescript': '>=4'
  'react-hot-toast@*':
    dependencies:
      'csstype': '^3.0.10'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
